# https://docs.travis-ci.com/user/tutorial/
# https://docs.travis-ci.com/user/languages/java/
# https://www.vogella.com/tutorials/TravisCi/article.html
language: java
os: linux
dist: focal
jdk:
  - openjdk11

install: mvn clean install -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn test jacoco:report coveralls:report -Pcoverage-travis -Dchecks.skip -Dmaven.javadoc.skip=true -B
  # Deploy Maven Site to GitHub (https://befrish.github.io/testdatamt)
  # http://maven.apache.org/plugins/maven-scm-publish-plugin/various-tips.html
  # https://blog.soebes.de/blog/2015/06/12/making-github-page-for-mojohaus/
  - mvn site site:stage -B
  - mvn scm-publish:publish-scm -B

cache:
  directories:
    - $HOME/.m2
